### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by taki1984** [jacobmarks/image-quality-issues#1]
Hi,

I'm trying to install the plugin using the following command from the docs:
`fiftyone plugins download https://github.com/jacobmarks/image-quality-issues/`

But, I'm getting the following error:

```Downloading jacobmarks/image-quality-issues...
Traceback (most recent call last):
  File "/opt/miniconda3/envs/genai_venv/bin/fiftyone", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/miniconda3/envs/genai_venv/lib/python3.12/site-packages/fiftyone/core/cli.py", line 4633, in main
    args.execute(args)
  File "/opt/miniconda3/envs/genai_venv/lib/python3.12/site-packages/fiftyone/core/cli.py", line 4616, in <lambda>
    parser.set_defaults(execute=lambda args: command.execute(parser, args))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genai_venv/lib/python3.12/site-packages/fiftyone/core/cli.py", line 3658, in execute
    fop.download_plugin(
  File "/opt/miniconda3/envs/genai_venv/lib/python3.12/site-packages/fiftyone/plugins/core.py", line 205, in download_plugin
    repo.download(tmpdir)
  File "/opt/miniconda3/envs/genai_venv/lib/python3.12/site-packages/fiftyone/utils/github.py", line 174, in download
    web_session.write(zip_path, zip_url)
  File "/opt/miniconda3/envs/genai_venv/lib/python3.12/site-packages/eta/core/web.py", line 147, in write
    r = self._get_streaming_response(url, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genai_venv/lib/python3.12/site-packages/eta/core/web.py", line 162, in _get_streaming_response
    raise WebSessionError("Unable to get '%s'" % url)
eta.core.web.WebSessionError: Unable to get 'https://api.github.com/repos/jacobmarks/image-quality-issues/zipball'
```

Any ideas of what could be wrong?

OS: MacOS
Env: Miniconda
Python: 3.12

Thanks :)

**Comment by jacobmarks** [comment]
Hey @taki1984 , sorry you're running into this. Someone from our team tried this yesterday and was unable to repro the issue. What version of FiftyOne are you using? And is this error popping up when you try to download other plugins?
